apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.capi.appName | default "capi" }}-service
  labels:
    app: {{ .Values.global.product }}
    tier: {{ .Values.capi.appName | default "capi" }}
spec:
  selector:
    app: {{ .Values.global.product }}
    tier: {{ .Values.capi.appName | default "capi" }}
  ports:
  - protocol: TCP
    name: main
    port: {{ .Values.capi.port | default 9080 }}
    targetPort: {{ .Values.capi.targetPort | default 9080 }}
  - protocol: TCP
    name: confagent
    port: {{ .Values.confAgentServer.port | default 8585 }}
    targetPort: {{ .Values.confAgentServer.targetPort | default 8585 }}
