appName: postgresql
postgresqlDataDir: /var/lib/pgsql/data
image:
  registry: docker-hub.middleware.biz

postgres:
  image:
    registry: docker-hub.middleware.biz
    repository: "/pg_schema"

  # if internal true - create and use internal postgres container
  # if internal false - enable external db, like aws rds
  internal: true
  ## secret configuration for postgresql
  ## pvc name
  persistantVolumeClaimName: "postgresql-pvc"
  secret:
    ## true - secret will be created automaticaly with provided values
    ## false - secret should be created manualy
    create: true
    ## secret name
    name: "postgresql-secret"
    ## for init db and roles dbsuperuser and dbuser cannot be changed (because used as plain text in sql)
    dbsuperuser: "postgres"
    ## password - for dbsuperuser
    dbsuperuserpwd: "Corezoid1234!"
    data:
      dbhost: "postgresql-service"
      dbport: 5432
      dbuser: "internal_user"
      dbpwd: "8hhgasdgiuf"
  ###### ATENTION! shards_count and shards cant be changed after first init!!!! ####
  # be careful in defining this variable
  # count of shards created in psql, if unset, default - 10
  shards_count: 10
  # count of shards created in psql, if unset, default - 10 - in array format
  shards: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
  # set false to disable if you don't want to use PGBouncer recommended - true
  bouncer: true
  bouncer_minReplicas: "1"
  bouncer_maxReplicas: "4"
  bouncer_resources:
    limits:
      cpu: "500m"
      memory: "500Mi"
    requests:
      cpu: "100m"
      memory: "100Mi"
  # Maximum number of client connections allowed.
  maxclientconn: "100000"
  # How many server connections to allow per user/database pair. Can be overridden in the per-database configuration.
  default_pool_size: "5000"
  # Server is released back to pool after transaction finishes. default: session, see man https://wiki.postgresql.org/wiki/PgBouncer
  # transaction | session
  default_pool_mode: transaction
  # Postgres corezoid schema version
  postgres_schema:
    version: "5.6.1"
  rotation:
    ## enabled: true or false
    enabled: true
    # tasks_archive table cleanup period in crontab format
    # minute hour day month dayofweek
    schedule: "0 0 1 * *"