appName: elasticsearch

image:
  registry: docker-hub.middleware.biz
  repository: /elasticsearch

elasticsearch:
  tag: "6.7.1"
  # if internal true - create and use internal elasticsearch container
  # if internal false - enable external elasticsearch, like aws elasticsearch service
  internal: true
  ## secret configuration for elasticsearch
  secret:
    ## true - secret will be created automaticaly with provided values
    ## false - secret should be created manualy
    create: true
    name: "elasticsearch-secret"
    data:
      host: "elasticsearch-master"
      ## be careful with port - in internal install used 9200, in aws uses 443
      port: 443