dependencies:
  - name: ingress
    version: "0.1.0"
    condition: global.ingress.enabled

  - name: redis
    version: "0.1.0"
    condition: global.redis.internal

  - name: elasticsearch
    version: "0.1.0"
    condition: global.elasticsearch.internal

  - name: rabbitmq-ha
    version: "1.35.0"
    condition: global.mq.internal

  - name: postgres
    version: "0.1.0"
    condition: global.db.internal

  - name: nfs-provisioner
    version: "1.4.0"
    condition: global.nfs.enabled

  - name: efs-provisioner
    version: "0.14.0"
    condition: global.efs.enabled

  - name: dumps
    version: "0.0.1"
    condition: global.store_dumps.enabled
