dependencies:
  - name: ingress
    version: "0.1.0"
    condition: global.ingress.enabled

  - name: redis
    version: "0.1.2"
    condition: global.redis.internal

  - name: elasticsearch
    version: "0.1.1"
    condition: global.elasticsearch.internal

  - name: rabbitmq
    version: "13.0.0"
    condition: global.mq.internal

  - name: postgres
    version: "0.1.0"
    condition: global.db.internal

  - name: nfs-provisioner
    version: "1.4.0"
    condition: global.nfs.enabled

  - name: efs-provisioner
    version: "0.14.0"
    condition: global.efs.enabled

  - name: dumps
    version: "0.0.1"
    condition: global.store_dumps.enabled

  - name: limits
    version: "1.0.1"

  - name: web
    version: "1.1.3"

  - name: syncapi
    version: "1.0.1"
    condition: global.syncapi.enabled

  - name: usercode
    version: "1.0.3"

  - name: worker
    version: "1.1.2"

  - name: capi
    version: "1.1.3"

  - name: conf-agent-server
    version: "1.0.2"

  - name: enigma-key-manager
    version: "0.1.0"
    condition: global.enigma.enabled

  - name: merchant
    version: "0.1.0"
    condition: global.merchant.enabled

  - name: mult
    version: "1.0.2"

  - name: pgbouncer
    version: "0.1.1"
    condition: global.db.bouncer

  - name: http-worker
    version: "1.0.2"

  - name: web-superadm
    version: "1.0.1"

  - name: postgres_schema
    version: "1.1.1"
