## @section Global parameters
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## @param global.imageRegistry Global Docker image registry
## @param global.imagePullSecrets Global Docker registry secret names as an array
## @param global.storageClass Global StorageClass for Persistent Volume(s)
##
global:
  imageRegistry: docker-hub.middleware.biz
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent
  storageClass: "corezoid-storage-class-efs-test"
  storage: efs
  domain: "devopsdev.corezoid.com"
  subdomain: "corezoid"
  product: "corezoid"
  error_log_level: debug

## Common parameters
## @param kubeVersion Override Kubernetes version
##
kubeVersion:
## @param nameOverride String to partially override common.names.fullname
##
nameOverride:
## @param fullnameOverride String to fully override common.names.fullname
##
fullnameOverride:
## @param commonLabels Labels to add to all deployed objects
##
commonLabels: {}
## @param commonAnnotations Annotations to add to all deployed objects
##
commonAnnotations: {}
## @param clusterDomain Kubernetes cluster domain name
##
clusterDomain: cluster.local
## @param extraDeploy Array of extra objects to deploy with the release
##
extraDeploy: []
## @param prometheus parameters
##
prometheus:
  path: "/metrics"
  port: "9100"
  scrape: "true"
## @param custom schedulerName https://kubernetes.io/docs/tasks/extend-kubernetes/configure-multiple-schedulers/
##
schedulerName: ""
## @section to define provisoner argocd | helm default: helm
provisoner: ""

ingress:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-1:305168114386:certificate/5fad3576-220b-4c69-ac85-e56b3fe684bd
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: "routing.http2.enabled=false"
   ## access restrictionkgec
   ## alb.ingress.kubernetes.io/inbound-cidrs: 8.8.8.8/32, 1.1.1.1/32, 0.0.0.0/0
   ## for creating route53 record-set
   ## external-dns.alpha.kubernetes.io/hostname: {{ .Values.global.subdomain}}.{{ .Values.global.domain }}

## @section CAPI Parameters

## CAPI
##
capi:
  name: capi
  ## @param image.registry CAPI image registry
  ## @param image.repository CAPI image repository
  ## @param image.tag CAPI image tag (immutable tags are recommended)
  ## @param image.pullPolicy CAPI image pull policy
  ## @param image.pullSecrets CAPI image pull secrets
  ##
  image:
    registry: docker-hub.middleware.biz
    repository: public/conveyor_api
    tag: "7.6.1.1"
    pullPolicy: IfNotPresent
    pullSecrets: []
  updateStrategy:
    type: RollingUpdate
  ## @param capi.terminationGracePeriodSeconds duration in seconds the CAPI pod needs to terminate gracefully. Defaults to 300 seconds.
  ##
  terminationGracePeriodSeconds: 10
  ## @param capi.replicaCount Number of CAPI replicas to deploy
  ##
  replicaCount: 2
  ## capi resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ## @param capi.resources.limits The resources limits for the CAPI containers
  ## @param capi.resources.requests The requested resources for the CAPI containers
  ##
  resources:
    limits:
      cpu: 1200m
      memory: 1500Mi
    requests:
      cpu: 50m
      memory: 50Mi
  ## @param capi.customLivenessProbe Custom livenessProbe that overrides the default one
  ##
  customLivenessProbe: {}
  ## @param capi.customReadinessProbe Custom readinessProbe that overrides the default one
  ##
  customReadinessProbe: {}
  ## @param capi.existingConfigmap The name of an existing ConfigMap with your custom configuration for CAPI
  ##
  existingConfigmap:
  ## @param capi.command Override default container command (useful when using custom images)
  ##
  command: []
  ## @param capi.args Override default container args (useful when using custom images)
  ##
  args: []
  ## https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/
  ##
  hostAliases: []
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
  ##
  podLabels: {}
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  ##
  podAnnotations: {}
  ## @param capi.podAffinityPreset Pod affinity preset. Ignored if `capi.affinity` is set. Allowed values: `soft` or `hard`
  ## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
  ##
  podAffinityPreset: ""
  ## @param capi.podAntiAffinityPreset Pod anti-affinity preset. Ignored if `capi.affinity` is set. Allowed values: `soft` or `hard`
  ## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
  ##
  podAntiAffinityPreset: soft
  ## Node capi.affinity preset
  ## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity
  ##
  nodeAffinityPreset:
    ## @param capi.nodeAffinityPreset.type Node affinity preset type. Ignored if `capi.affinity` is set. Allowed values: `soft` or `hard`
    ##
    type: ""
    ## @param capi.nodeAffinityPreset.key Node label key to match. Ignored if `capi.affinity` is set
    ##
    key: ""
    ## @param capi.nodeAffinityPreset.values Node label values to match. Ignored if `capi.affinity` is set
    ## E.g.
    ## values:
    ##   - e2e-az1
    ##   - e2e-az2
    ##
    values: []
  ## @param capi.affinity Affinity for CAPI pods assignment
  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  ## NOTE: `capi.podAffinityPreset`, `capi.podAntiAffinityPreset`, and `capi.nodeAffinityPreset` will be ignored when it's set
  ##
  affinity: {}
  ## @param capi.nodeSelector Node labels for CAPI pods assignment
  ## ref: https://kubernetes.io/docs/user-guide/node-selection/
  ##
  nodeSelector: {}
  ## @param capi.tolerations Tolerations for CAPI pods assignment
  ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  ##
  tolerations: []
  ## @param capi.updateStrategy.type CAPI statefulset strategy type
  ## ref: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies
  ##
  ## @param capi.priorityClassName CAPI pods' priorityClassName
  ##
  priorityClassName: ""
  ## @param capi.lifecycleHooks for the CAPI container(s) to automate configuration before or after startup
  ##
  lifecycleHooks: {}
  ## @param capi.extraEnvVars Array with extra environment variables to add to CAPI nodes
  ## e.g:
  ## extraEnvVars:
  ##   - name: FOO
  ##     value: "bar"
  ##
  extraEnvVars: []
  ## @param capi.extraEnvVarsCM Name of existing ConfigMap containing extra env vars for CAPI nodes
  ##
  extraEnvVarsCM:
  ## @param capi.extraEnvVarsSecret Name of existing Secret containing extra env vars for CAPI nodes
  ##
  extraEnvVarsSecret:
  ## @param capi.extraVolumes Optionally specify extra list of additional volumes for the CAPI pod(s)
  ##
  extraVolumes: []
  ## @param capi.extraVolumeMounts Optionally specify extra list of additional volumeMounts for the CAPI container(s)
  ##
  extraVolumeMounts: []
  ## @param capi.sidecars Add additional sidecar containers to the CAPI pod(s)
  ## e.g:
  ## sidecars:
  ##   - name: your-image-name
  ##     image: your-image
  ##     imagePullPolicy: Always
  ##     ports:
  ##       - name: portname
  ##         containerPort: 1234
  ##
  sidecars: {}
  ## @param capi.initContainers Add additional init containers to the CAPI pod(s)
  ## ref: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
  ## e.g:
  ## initContainers:
  ##  - name: your-image-name
  ##    image: your-image
  ##    imagePullPolicy: Always
  ##    command: ['sh', '-c', 'echo "hello world"']
  ##
  initContainers: {}
  ##
  ##
  autoscaling:
    enabled: truecontainerPort
    minReplicas: 2
    maxReplicas: 4
    targetCPU: 65
    targetMemory: 1000Mi
    requests:
  service:
    ## @param capi.service.capiPort CAPI service port number. Default: 80
    ##
    capiPort: 9080
    ## @param capi.service.confAgentPort confAgentPort service port number. Default: 8585
    ##
    confAgentPort: 8585
  ## CAPI aplication parameters
  ##
  schedulers: 1
  capi_front_captcha_key: "kfvdsm;v"
  capi_backend_captcha_key: "ldsnvlsdn"
  registration_restriction:
    enable: false
    allowed_domains:
      - "gmail.com"
      - "yahoo.com"
  ## Сaptcha when login in UI enable/disable
  capi_front_captcha_disabled: true
  max_task_size_for_process_conv: 264000
  max_task_size_for_st_diagramm_conv: 264000
  ## max req/sec of create|modify|delete for conv|folder|dashboard in 1 sec
  max_reqs_limit: 50000
  ## merchant_api settings
  merchant_api:
    skip_otp: true
  ## cookie expire time in sec (default 900)
  cookie_expr_time: 7200
  ## Setting for configure frontend
  front_setting:
    ## documentation (navigate by clicking on DOCS link)
    doc_host: "doc.corezoid.com"
    doc_index: "/"
    ui:
      ## enabled Market button
      market: false
      ## button Create -> Bot platform
      bot_platform: false
      ## billing button display
      billing: false
      ## display of the git_call button
      git_call: false
      ## set default company name
      default_company: "My Corezoid"
      ## Tab name
      tab_name: "Corezoid"
      ## disable or enable logo on main page
      disabled_auth_logo: false
      ## colors
      color_main: "#0791e5"
      color_logo: "#0791e5"
      color_logo_hover: "#056cab"
  ldap_server: "ldap.middleware.loc"
  ldap_port: "389"
  ldap_base: "ou=people,o=middleware"
  ldap_filter: "uid"
  ## then this param is true, bind_user_name, bind_user_pass should be filled. if it's false it is not necessary
  ldap_first_bind_user: true
  ldap_bind_user_name: "uid=ldap,ou=people,o=middleware"
  ldap_bind_user_pass: ""
  ldap_user_nick_entry: "cn"
  ldap_tls: false
  logic_settings:
   ## max allowed threads for api logic
    api_max_thread: 50000
    sender_max_threads: 25
    timer_default: 5
  ## enigma private_key_id
  enigma_pk_id: ""

## ConfAgentServer
##
confAgentServer:
  name: conf-agent-server
  image:
    registry: docker-hub.middleware.biz
    repository: public/conf_agent_server
    tag: "1.5.2-without-tini"
    pullPolicy: IfNotPresent
    pullSecrets: []
  replicaCount: 2
  terminationGracePeriodSeconds: 10
  resources:
    limits:
      cpu: 1200m
      memory: 1500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPU: 65
    targetMemory: 80
    requests:
  service:
    ## confAgentServerPort Port default: 80
    ##
    confAgenttPort: 8585

## http-worker
##
http:
  name: http-worker
  image:
    registry: docker-hub.middleware.biz
    repository: public/http-worker
    tag: "master-kub"
    pullPolicy: IfNotPresent
    pullSecrets: []
  replicaCount: 1
  terminationGracePeriodSeconds: 40
  resources:
    limits:
      cpu: 4000m
      memory: 4000Mi
    requests:
      cpu: 100m
      memory: 100Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 4
    targetCPU: 65
    targetMemory:
    requests:
  schedulers: 2
  max_http_resp_size: "5242880"
  blocked_domains:
    - "169.254.169.254"
    - "mail.ru"
  tune:
    http_consumer_queues_count: 8
    http_consumer_connections_per_queue: 1
    http_consumer_channels_per_connection: 1
    http_consumer_messages_prefetch_size_per_channel: 20
    consumer_settings_messages_prefetch_size_per_channel: 50
    consumer_response_prefetch_size_per_channel: 50
  affinity: {}

## Syncapi
##
syncapi:
  name: "syncapi"
  subdomain: "syncapi"
  image:
    registry: docker-hub.middleware.biz
    repository: public/corezoid_api_sync
    tag: "2.0.4"
    pullSecrets: []
  replicaCount: 1
  autoscaling:
    enabled: false
  service:
    ## syncapi port default: 80
    syncapiPort: 8090
  schedulers: 2

## Webadm
##
webadm:
  name: webadm
  image:
    registry: docker-hub.middleware.biz
    repository: public/conveyor_adm_web
    tag: "5.6.1"
    pullSecrets: []
  replicaCount: 2
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 50m
      memory: 50Mi
  autoscaling:
    enabled: false
  affinity: {}
  service:
    ## webadm port default: 80
    ##
    port: 80

## Web Superadm
##
websuperadm:
  name: "web-superadm"
  subdomain: "superadm"
  image:
    registry: docker-hub.middleware.biz
    repository: public/conf_agent_admin
    tag: "1.5.1"
    pullPolicy: IfNotPresent
    pullSecrets: []
  replicaCount: 2
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 50m
      memory: 50Mi
  autoscaling:
    enabled: false
  service:
    ## websuperadm port default: 80
    ##
    port: 80

## Worker
##
worker:
  name: worker
  image:
    registry: docker-hub.middleware.biz
    repository: public/conveyor-worker
    tag: "4.6.1.0-without-tini"
    pullPolicy: IfNotPresent
    pullSecrets: []
  replicaCount: 2
  resources:
    limits:
      cpu: 1000m
      memory: 1500Mi
    requests:
      cpu: 150m
      memory: 150Mi
  autoscaling:
    enabled: false
  schedulers: 2

## Merchant
##
merchant:
  name: merchant
  image:
    registry: docker-hub.middleware.biz
    repository: public/merchant
    tag: "v0.0.27.2"
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources:
    limits:
      cpu: 500m
      memory: 800Mi
    requests:
      cpu: 100m
      memory: 100Mi
  autoscaling:
    enabled: false
  service:
    ## merchant port default: 80
    ##
    merchantPort: 8080
    ## managment port default: 7980
    ##
    managmentPort: 7980
  merchant_login: "apiLogin1"
  merchant_secret: "I9EmB170XUbe"

## Limits
##
limits:
  name: limits
  image:
    registry: docker-hub.middleware.biz
    repository: public/corezoid_limits
    tag: "1.2.2-without-tini"
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources:
    limits:
      cpu: 500m
      memory: 800Mi
    requests:
      cpu: 50m
      memory: 50Mi
  service:
    ## limits port default: 80
    ##
    limitsPort: 8585

## Mult
##
mult:
  name: mult
  image:
    registry: docker-hub.middleware.biz
    repository: public/conveyor_api_multipart
    tag: "2.5.1.0"
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources:
    limits:
      cpu: 500m
      memory: 800Mi
    requests:
      cpu: 50m
      memory: 50Mi
  autoscaling:
    enabled: false
  service:
    ## mult port default: 80
    ##
    multPort: 9082
  ## pvc name if it already exist or was created manualy
  ##
  persistantVolumeClaimName: "mult-pvco"
  ## true if pvc for mult should be created automaticaly
  ## false if you already have pvc
  ##
  persistantVolumeClaimCreate: true
  ## application resources limits and requests
  ## enigma private_key_id
  ##
  enigma_pk_id: ""

## Usercode
##
usercode:
  name: usercode
  image:
    registry: docker-hub.middleware.biz
    repository: public/usercode
    tag: "7.2.1"
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources:
    limits:
      cpu: 1000m
      memory: 1000Mi
    requests:
      cpu: 50m
      memory: 50Mi
  autoscaling:
    enabled: false
  ## enigma private_key_id
  ##
  enigma_pk_id: ""
  affinity: {}

## SA
##
sa:
 ## true or false
  enabled: false
  google_client_id: 8888

## SA WEB
##
sa_web:
  subdomain: "sa"

## GitCall
##
gitcall:
 ## true or false
  enabled: false
  mq_vhost: "/gitcall"
  dunder_mq_vhost: "/dundergitcall"

## Enigma
##
enigma:
  enabled: false
  encryption: false

## Store Dumps
##
store_dumps:
  enable: true

## Redis
##
externalRedis:
  ## Name of existing secret object
  ##
  ## existingSecret: "redis-secret"
  host: "redis-master.corezoid-service-test.svc.cluster.local"
  port: "6379"
  password: ""
  host_cache: "redis-master.corezoid-service-test.svc.cluster.local"
  port_cache: "6379"
  password_cache: ""
  host_timers: "redis-master.corezoid-service-test.svc.cluster.local"
  port_timers: "6379"
  password_timers: ""

## Rabbitmq
##
externalRabbitmq:
  ## Name of existing secret object
  ##
  ## existingSecret: "rabbitmq-secret"
  host: "rabbit-service.corezoid-service-test.svc.cluster.local"
  port: "5672"
  vhost: "/conveyor"
  username: "rabbitUser"
  password: "rabbitPassword"
  rabbitmqErlangCookie: ""

## Elasticsearch
##
externalElasticsearch:
  host: "http://elasticsearch-service.corezoid-service-test.svc.cluster.local"
  port: "9200"

## Postgres
##
postgres:
  internal: false
  ## secret configuration for postgresql

  ## pvc name
  persistantVolumeClaimName: "postgresql-pvc"
  postgresRoot: "postgres"
  postgresRootPassword: "postgresRootPassword"
  postgresHost: "postgres-service.corezoid-service-test.svc.cluster.local"
  postgresPort: "5432"
  postgresUser: "internal_user"
  postgresPassword: "postgresPassword"

  ###### ATENTION! shards_count and shards cant be changed after first init!!!! ####
 ## be careful in defining this variable
 ## count of shards created in psql, if unset, default - 10
  shards_count: 10
 ## count of shards created in psql, if unset, default - 10 - in array format
  shards: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]

 ## set false to disable if you don't want to use PGBouncer recommended - true
  bouncer: false
  bouncer_minReplicas: "4"
  bouncer_maxReplicas: "4"
  bouncer_resources:
    limits:
      cpu: "500m"
      memory: "500Mi"
    requests:
      cpu: "500m"
      memory: "500Mi"
 ## Maximum number of client connections allowed.
  maxclientconn: "100000"
 ## How many server connections to allow per user/database pair. Can be overridden in the per-database configuration.
  default_pool_size: "5000"
 ## Server is released back to pool after transaction finishes. default: session, see man https://wiki.postgresql.org/wiki/PgBouncer
 ## transaction | session
  default_pool_mode: transaction

 ## Postgres corezoid schema version
  postgres_schema:
    version: "5.6.1"

  rotation:
    ## enabled: true or false
    enabled: true
   ## tasks_archive table cleanup period in crontab format
   ## minute hour day month dayofweek
    schedule: "0 0 1 * *"
