appName: pgbouncer
image:
  registry: hub.corezoid.com
  repository: public/pgbouncer
  tag: 1.23.1-alpine3.21-1

exporterImage:
  registry: hub.corezoid.com
  repository: public/prometheus-pgbouncer-exporter
  tag: 2.1.1-python3.7.17-alpine3.18