{{- if .Values.rabbitmq.secret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rabbitmq.secret.name}}
  labels:
    app: {{ .Values.global.product }}
    tier: "rabbitmq"
type: Opaque
stringData:
  {{- range $key, $value := .Values.rabbitmq.secret.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
