{{- if .Values.mult.persistantVolumeClaimCreate }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.mult.persistantVolumeClaimName }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "corezoid.labels.standard" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "corezoid.mult" . }}
    app.kubernetes.io/component: {{ .Values.mult.name }}
    app: {{ .Values.global.product }}
  {{- if eq .Values.global.storage "efs" }}
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.global.storageClass }}
{{- end }}
spec:
  storageClassName: {{ .Values.global.storageClass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
{{- end }}
