apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.worker.appName }}-autoscale
  labels:
    app: {{ .Values.global.product }}
    tier: {{ .Values.worker.appName }}
spec:
  minReplicas: {{ .Values.http.minReplicas }}
  maxReplicas: {{ .Values.http.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.worker.appName }}-deployment
  targetCPUUtilizationPercentage: 60
