{{- if .Values.global.mq.secret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.mq.secret.name}}
  labels:
    app: {{ .Values.global.product }}
    tier: "rabbitmq"
type: Opaque
data:
  api_port: {{ .Values.global.mq.secret.data.api_port | default "15672" | b64enc | quote }}
  api_scheme: {{ .Values.global.mq.secret.data.api_scheme | default "http" | b64enc | quote }}
  host: {{ .Values.global.mq.secret.data.host | b64enc | quote }}
  password: {{ .Values.global.mq.secret.data.password | b64enc | quote }}
  port: {{ .Values.global.mq.secret.data.port | default "5672" | b64enc | quote }}
  rabbitmqErlangCookie: {{ .Values.global.mq.secret.data.rabbitmqErlangCookie | default "" | b64enc | quote }}
  username: {{ .Values.global.mq.secret.data.username | b64enc | quote }}
  vhost: {{ .Values.global.mq.secret.data.vhost | default "/conveyor" | b64enc | quote }}
{{- end}}

{{- if hasKey .Values.global "mq_http" }}
{{- if .Values.global.mq_http.secret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.mq_http.secret.name}}
  labels:
    app: {{ .Values.global.product }}
    tier: "rabbitmq-http"
type: Opaque
data:
  api_port: {{ .Values.global.mq_http.secret.data.api_port | default "15672" | b64enc | quote }}
  api_scheme: {{ .Values.global.mq_http.secret.data.api_scheme | default "http" | b64enc | quote }}
  host: {{ .Values.global.mq_http.secret.data.host | b64enc | quote }}
  password: {{ .Values.global.mq_http.secret.data.password | b64enc | quote }}
  port: {{ .Values.global.mq_http.secret.data.port | default "5672" | b64enc | quote }}
  rabbitmqErlangCookie: {{ .Values.global.mq_http.secret.data.rabbitmqErlangCookie | default "" | b64enc | quote }}
  username: {{ .Values.global.mq_http.secret.data.username | b64enc | quote }}
  vhost: {{ .Values.global.mq_http.secret.data.vhost | default "/conveyor" | b64enc | quote }}
{{- end}}
{{- end}}