{{- if .Values.global.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: corezoid-mult-policy
  labels:
    app: {{ .Values.global.product }}
    tier: {{ .Values.appName }}
spec:
  podSelector:
    matchLabels:
      tier: mult
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              tier: capi
    - from:
        - podSelector:
            matchLabels:
              tier: corezoid-web-adm
    - from:
        - podSelector:
            matchLabels:
              tier: mult
{{ .Values.global.networkPolicy.labelsSelector.ingress | toYaml | indent 4 }}
{{ .Values.global.networkPolicy.labelsSelector.monitoring | toYaml | indent 4 }}
{{- end }}