---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: {{ .Values.global.product }}
    tier: "postgres"
  annotations:
    {{- include "corezoid.provisoner.configmap" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_DBHOST: {{ .Values.postgres.postgresHost | b64enc | quote }}
  POSTGRES_DBUSER: {{ .Values.postgres.postgresUser | b64enc | quote }}
  POSTGRES_DBPWD: {{ .Values.postgres.postgresPassword | b64enc | quote }}
  POSTGRES_DBPORT: {{ .Values.postgres.postgresPort | b64enc | quote }}
  SPRING_DATASOURCE_URL: {{ .Values.postgres.postgresHost | b64enc | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.postgres.postgresUser | b64enc | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.postgres.postgresPassword | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret-root
  labels:
    app: {{ .Values.global.product }}
    tier: "postgres"
  annotations:
  {{- include "corezoid.provisoner.configmap" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_DBHOST: {{ .Values.postgres.postgresHost | b64enc | quote }}
  POSTGRES_DBSUPERUSER: {{ .Values.postgres.postgresRoot | b64enc | quote }}
  POSTGRES_DBSUPERUSERPWD: {{ .Values.postgres.postgresRootPassword | b64enc | quote }}
  POSTGRES_DBPORT: {{ .Values.postgres.postgresPort | b64enc | quote }}



