apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-init-database
  labels:
    app: {{ .Values.global.product }}
    tier: postgres-job
  annotations:
    {{- include "corezoid.provisoner.job" . | nindent 4 }}
spec:
  template:
    metadata:
      name: postgres-init-database
      labels:
        app: {{ .Values.global.product }}
        tier: postgres-job
    spec:
      restartPolicy: OnFailure
      containers:
        - image: "{{ .Values.global.imageRegistry }}/public/pg_schema:{{ .Values.postgres.postgres_schema.version }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy | default "IfNotPresent" }}
          name: postgres-initdb
          command: ["/bin/sh"]
          args: ["-c", "/postgres-schema-versioner/run.sh"]
          env:
            - name: SCHEMA_VERSION
              value: {{ .Values.postgres.postgres_schema.version }}
            - name: SHARD_COUNT
              value: '{{ .Values.postgres.shards_count }}'
          envFrom:
            - secretRef:
                name: postgres-secret-root
            - secretRef:
                name: postgres-secret
