{{- if not .Values.externalRabbitmq.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  labels:
    app: {{ .Values.global.product }}
    tier: "rabbitmq"
  annotations:
    {{- include "corezoid.provisoner.configmap" . | nindent 4 }}
type: Opaque
data:
  MQ_HOST: {{ .Values.externalRabbitmq.host | b64enc | quote }}
  MQ_PORT: {{ .Values.externalRabbitmq.port | b64enc | quote }}
  MQ_USERNAME: {{ .Values.externalRabbitmq.username | b64enc | quote }}
  MQ_PASSWORD: {{ .Values.externalRabbitmq.password | b64enc | quote }}
  MQ_VHOST: {{ .Values.externalRabbitmq.vhost | b64enc | quote }}
{{- end}}
