{{- if .Values.redis.secret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.secret.name}}
  labels:
    app: {{ .Values.product }}
    tier: "redis"
type: Opaque
data:
  {{- range $key, $value := .Values.redis.secret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end}}
