{{- if not .Values.externalRedis.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  labels:
    app: {{ .Values.global.product }}
    tier: "redis"
  annotations:
    {{- include "corezoid.provisoner.configmap" . | nindent 4 }}
type: Opaque
data:
  REDIS_HOST: {{ include "corezoid.redis.host" . | b64enc | quote }}
  REDIS_PORT: {{ include "corezoid.redis.port" . | b64enc | quote }}
  REDIS_PASSWORD: {{ include "corezoid.redis.rawPassword" . | b64enc | quote }}
  REDIS_HOST_CACHE: {{ include "corezoid.redisCache.host" . | b64enc | quote }}
  REDIS_PORT_CACHE: {{ include "corezoid.redisCache.port" . | b64enc | quote }}
  REDIS_PASSWORD_CACHE: {{ include "corezoid.redisCache.rawPassword" . | b64enc | quote }}
  REDIS_HOST_TIMERS: {{ include "corezoid.redisTimers.host" . | b64enc | quote }}
  REDIS_PORT_TIMERS: {{ include "corezoid.redisTimers.port" . | b64enc | quote }}
  REDIS_PASSWORD_TIMERS: {{ include "corezoid.redisTimers.rawPassword" . | b64enc | quote }}
  SPRING_REDIS_HOST: {{ include "corezoid.redis.host" . | b64enc | quote }}
  SPRING_REDIS_PORT: {{ include "corezoid.redis.port" . | b64enc | quote }}
  SPRING_REDIS_PASSWORD: {{ include "corezoid.redis.rawPassword" . | b64enc | quote }}
{{- end }}
